### ISSUE TITLE
EPIC: Pairing results to apply Multiple features and fix bugs

### ISSUE THREAD

**Issue by avdata99** [datopian/ckan-ng-harvest#4]
### Harvester-core Python Library:

 - [x] Automate core deploy to Pypi
 - [x] Automate core test running on each commit
   - [x] Use GitLab CI (to run test at core library: `python -m pytest tests`)
 - [x] Move all stuff that's not part of the core library outside:
   - [x] harvested_source.py uses data files that are generated outside of the library
   - [x] The config.py at core saves files with names as _flow*.json_ but the clients are not going to underestan this.
 - [x] One folder for each harvest type at [core/harvester/](https://gitlab.com/datopian/ckan-ng-harvester-core/blob/master/harvester/)
 - [x] Create a class for inherit all the harvester sources classes
 - [ ] Document in README the interface for _loaders_ and _adapters_
 - [x] json-schema library to validate all data.json
 - [x] Use tox for running tests (moved to #65)
 - [x] Add LICENSE file (MIT) [DONE]
 - [x] add .pytest_cache to .gitignore and out of the repo [DONE]
 - [x] Change API to use Exceptions and not return values (to check success)
 
### ckan-ng-harvest

 - [x] Move utility scripts to tools/ folder
   - [x] analyze_harvest_sources.py
     - [x] remove harvest_datasets_datagov_analysis.csv. []
 - [x] create_full_report.py
 - [x] read_harvest_sources (analyze to delete)
 - [x] import_harvest_sources
   - [x] We could run this from an external computer
   - [x] Remove from dags
 - [x] Delete unused/Garbage files
   - [x] harvest_datasets_datagov_analysis.csv
 - [x] Replace GPL License with MIT
 - [x] Remove settings.py/local_settings files, use _envs_.
 - [x] Tests
   - [x] Run tests in CI on each commit
   - [x] Move test related scripts to tests/ folder
     - [x] test*.sh
     - [x] each harvester/tests -> /tests/
 - [x] Move _public_ to _/tests/samples_ and ensure mock all request. (moved to #65)
 - [x] Move _samples_ in each harvester folder to _tests/samples_ (moved to #65)
 - [x] Move _imgs_ to _docs_ folder.
 - [x] add .pytest_cache to .gitignore and out of the repo
 - [x] Move harvest.py on each harvest type to _harvest_ forlder, outside. Use a father class for this and implement different parameters for each harvest type.

### Harvesters:
 - [x] flow, flow2, flow3, functions{,1,2}:
   - [x] change to meaningful names
   - [x] create one class, with 3 methods (one for each flow) and helper methods/classes as necessary
   - [ ] don't do argument parsing in it - use method parameters
 - [x] functions:
   - [x] Use a common try...except...finally to handle errors, and not error value checking
     - [x] e.g. get_data_json_from_url()
 - [x] remove all code duplication!
 - [x] create_report / analyze_sources.py
   - [x] move to tools / funciton classes

### Dags

 - [ ] automate-dags/../dags:
   - [x] remove import_harvest_sources_with_airflow.py file and DAGs
   - [x] Create one DAG for each source, not for each frequency. [DONE, is a much more heavy proccess now]
   - [x] Skip bad frequencies at harvest_with airflow, or better, use defautls values. [DONE]
   - [ ] Analyze to use PythonOperator and remove the BashOperator: Started [here](https://github.com/datopian/ckan-ng-harvest/tree/63_python_operator). Continued in #20.

### Docker compose

 - [x] Move to LocalExecutor instead of CeleryExecutor [DONE [here](https://gitlab.com/datopian/ckan-ng-harvest/commit/aaecd0b40dc71ef8f6a0b46d0719b62e4e0b0303)]
 - [x] Move to explicit env vars istead of envfiles [DONE]

**Comment by kimwdavidson** [comment]
@estebanruseler to create tickets for remaining issues, which we'll then prioritize

**Comment by avdata99** [comment]
The Bash operator was moved to #20
The tests were moved to #200, #201, #202, and #203

Ready to close

**Comment by estebanruseler** [comment]
I had a co-working session with Adam and Andres to align on this issue and what works is outstanding. The following 3 issues have not been completed, and have new issues created. 


* Python lib - Document in README the interface for loaders and adapters --> New issue : https://github.com/datopian/ckan-ng-harvest/issues/21
* Harvesters - "don't do argument parsing in it - use method parameters" --> https://github.com/datopian/ckan-ng-harvest/issues/22
* Dags - Analyze to use PythonOperator and remove the BashOperator --> New issue: https://github.com/datopian/ckan-ng-harvest/issues/20

In addition, Julie has 4 testing issues 200,201,202,203

FYI This is the [original issue that was created in gitlab](https://gitlab.com/datopian/ckan-ng-harvest/issues/63)I had a co-working session with Adam and Andres to align on this issue and what works is outstanding. The following 3 issues have not been completed, and have new issues created.
