### ISSUE TITLE
Improve tests coverage

### ISSUE THREAD

**Issue by avdata99** [datopian/ckan-ng-harvest#5]
[After fix permissions: assign to @thejuliekramer]

Where are in the middle of a refactor (it's almost done) defined at #63.
Until [the pending PR](https://gitlab.com/datopian/ckan-ng-harvest/merge_requests/70) is approved you can work in a new branch from 64_harvest_with_config.

### Tasks

* [ ] Use tox for running tests (from #4)
* [ ] Move *public* to */tests/samples* and ensure mock all request. (from #4)
* [ ] Move *samples* in each harvester folder to *tests/samples* (from #4)
* [ ] Update tests_with_ckan from DataJSON to work with the new classes.
* [ ] Measure and increase the test coverage

Ensure to update the [Gitlab CI file](https://gitlab.com/datopian/ckan-ng-harvest/blob/develop/.gitlab-ci.yml) if necessary.

The CSW harvester is not migrated after the core library refactor, so is not working and is not part of this issue

**Comment by kimwdavidson** [comment]
Duplicate of #201, #202, #203. Closing
