### ISSUE TITLE
Set up a CI environment

### ISSUE THREAD

**Issue by avdata99** [datopian/ckan-ng-harvest#8]
Since we are moved from GitLab to GitHub we will need a CI environment

### Tasks

* [x] Check the tasks at [.gitlab-ci.yml](https://gitlab.com/datopian/ckan-ng-harvest/blob/develop/.gitlab-ci.yml)
* [x] Define a new environment: **Travis**
* [x] Apply and test
* [x] Remove referentes to GitLab and GitLHub CI

**Comment by thejuliekramer** [comment]
Set up environment to run tests without ckan https://github.com/datopian/ckan-ng-harvest/pull/10/checks tests and flake8 are passing

**Comment by avdata99** [comment]
We need to check and replace all the task in the previous [gitlab CI file](https://github.com/datopian/ckan-ng-harvest/blob/develop/.gitlab-ci.yml)

For example, to build and push the _viderum/ckan-ng-harvest_ image to docker registry.
We are going to need to add the credentials here @akariv

**Comment by avdata99** [comment]
We expect to compile docker image here: https://github.com/GSA/datagov-ckan-multi/issues/193#issuecomment-569090685

**Comment by akariv** [comment]
@avdata99 I added you as collaborator in docker hub, you should be able to push the image from the CI using your credentials.

**Comment by avdata99** [comment]
Done here: https://github.com/datopian/ckan-ng-harvest/blob/develop/.github/workflows/dockerimage.yml @akariv 

Worked [OK](https://github.com/datopian/ckan-ng-harvest/runs/365439603)
Pushed [OK](https://hub.docker.com/repository/docker/viderum/ckan-ng-harvest)

**Comment by kimwdavidson** [comment]
document Datopian policy

**Comment by avdata99** [comment]
PR sent @akariv @woodt @thejuliekramer

**Comment by avdata99** [comment]
Closing since the PR was approved and merged
